CarrierAccount.vzw_private_test.update carrier_account_name:    'Verizon Private Test'
CarrierAccount.vzw_private_primary.update carrier_account_name: 'Verizon Private Primary'
CarrierAccount.vzw_private_ab.update carrier_account_name:      'Verizon Private AB'
CarrierAccount.vzw_dia.update carrier_account_name:             'Verizon DIA'
CarrierAccount.vzw_public.update carrier_account_name:          'Verizon Public'
CarrierAccount.att_all.update carrier_account_name:             'AT&T All'
CarrierAccount.vdf_all.update carrier_account_name:             'Vodafone All'
CarrierAccount.swa_all.update carrier_account_name:             'Sierra All'
CarrierAccount.tmo_all.update carrier_account_name:             'T-Mobile All'
CarrierAccount.tls_all.update carrier_account_name:             'Telus All'
